name: Auto-format
on: issue_comment

jobs:
  report:
    runs-on: ubuntu-latest
    # Run this workflow when a comment is created on a pull request and the comment is equal to
    # 'auto-format'
    if: ${{ github.event.issue.pull_request && github.event.comment.body == 'auto-format' }}
    steps:
      - uses: actions/github-script@v3
        id: get-pr
        with:
          script: |
            const request = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            }
            core.info(`Getting PR #${request.pull_number} from ${request.owner}/${request.repo}`)
            try {
              const result = await github.pulls.get(request)
              return result.data
            } catch (err) {
              core.setFailed(`Request failed with error ${err}`)
            }
      - uses: actions/checkout@v2
        with:
          repository: ${{ fromJSON(steps.get-pr.outputs.result).head.repo.full_name }}
          ref: ${{ fromJSON(steps.get-pr.outputs.result).head.sha }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - uses: actions/setup-python@v2
        with:
          python-version: "3.6"
      - name: Install black
        run: |
          pip install black==19.10b0
      - name: Run black
        run: |
          black .
      - name: Push commit
        run: |
          git config --global user.name 'mlflow-automation'
          git config --global user.email 'mlflow-automation@users.noreply.github.com'
          git commit -sam "Auto format"
          git remote -v
          # git push origin HEAD:${{ fromJSON(steps.get-pr.outputs.result).head.repo.full_name }}
